name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.static_web_app_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Clean workspace
        run: |
          rm -rf node_modules
          rm -rf dist
          rm -rf .next
          rm -rf .cache
          rm -rf build
      
      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: false
          NODE_ENV: production
      
      - name: Prepare deployment directory
        run: |
          # Create a clean build directory
          rm -rf build
          mkdir -p build/assets
          
          # Copy only the essential files
          cp dist/index.html build/
          cp dist/assets/* build/assets/
          cp staticwebapp.config.json build/
          
          # Remove any unnecessary files and hidden files
          find build -type f -name "*.map" -delete
          find build -type f -name "*.ts" -delete
          find build -type f -name "*.tsx" -delete
          find build -type f -name "*.test.*" -delete
          find build -type f -name "*.spec.*" -delete
          find build -type f -name ".*" -delete
          find build -type d -name ".*" -exec rm -rf {} +
          
          # Remove any empty directories
          find build -type d -empty -delete
      
      - name: Debug - List deployment contents
        run: |
          echo "=== Build Directory Contents ==="
          ls -la build
          echo "=== Build File Count ==="
          find build -type f | wc -l
          echo "=== Build Directory Size ==="
          du -sh build
          echo "=== All Files in Build Directory ==="
          find build -type f
      
      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "build"
          app_build_command: "npm run build"
          api_location: ""
          api_build_command: ""
          deployment_environment: "Production"
          skip_app_build: true
          is_static_export: true
          app_artifact_location: "build"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
