name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Clean workspace
        run: |
          rm -rf node_modules
          rm -rf dist
          rm -rf .next
          rm -rf .cache
      
      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: false
          NODE_ENV: production
      
      - name: Debug - List workspace contents
        run: |
          echo "=== Workspace Contents ==="
          ls -la
          echo "=== Node Modules Contents ==="
          ls -la node_modules || echo "No node_modules found"
          echo "=== Dist Contents ==="
          ls -la dist || echo "No dist found"
          echo "=== File Counts ==="
          find . -type f | wc -l
          echo "=== Dist File Counts ==="
          find dist -type f | wc -l
          echo "=== Node Modules File Counts ==="
          find node_modules -type f | wc -l
      
      - name: Clean dist directory
        run: |
          find dist -type f -name "*.map" -delete
          find dist -type f -name "*.ts" -delete
          find dist -type f -name "*.tsx" -delete
          find dist -type f -name "*.jsx" -delete
          find dist -type d -name "node_modules" -exec rm -rf {} +
          # Remove any hidden files
          find dist -type f -name ".*" -delete
          # Remove any backup files
          find dist -type f -name "*~" -delete
          # Remove any temp files
          find dist -type f -name "*.tmp" -delete
          # Remove any log files
          find dist -type f -name "*.log" -delete
      
      - name: Debug - List final dist contents
        run: |
          echo "=== Final Dist Contents ==="
          ls -la dist
          echo "=== Final Dist File Count ==="
          find dist -type f | wc -l
      
      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"
          app_build_command: "npm run build"
          api_location: ""
          api_build_command: ""
          deployment_environment: "production"
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
